#!/bin/sh

sudo systemctl restart bluetooth.service
while ! bluetoothctl connect 74:A3:4A:F1:C2:42; do
  echo "Bluetooth not ready"
  sleep 0.5
done
index=$(pacmd list-sinks | grep index | tail -1 | awk '{print $2}')
while ! pacmd set-default-sink $index; do
  echo "Sink not ready"
  sleep 0.5
done
