#!/bin/sh

GREEN='\033[0;32m'
NC='\033[0m'
IP=$1

target-ip set $IP
export TARGET=$IP

for dir in scan scripts doc resources local
do
  mkdir -p $IP/$dir
done

echo "${GREEN}[+] Server IP: $IP"
echo "[+] OS: $(whichos $IP)"
echo "[+] Looking for open TCP ports...${NC}"
nmap -p- $IP -Pn --open -T5 -vvvvv -oX $IP/scan/all_tcp.xml | grep "Discovered open"
echo "${GREEN}[+] Scanning services on open TCP ports...${NC}"
nmap $(nmap-parser -p $IP/scan/all_tcp.xml) -A -T5 -Pn $IP -oN $IP/scan/open_tcp.nmap > /dev/null &
echo "${GREEN}[+] Scanning vulns on open TCP ports...${NC}"
nmap $(nmap-parser -p $IP/scan/all_tcp.xml) -T5 --script="vuln" $IP -oN $IP/scan/vuln_tcp.nmap > /dev/null &
wait
