#!/bin/sh

mode=$1
service=$2
pattern=$3

usage="usage: $0 [mode:find|gen] ..."
find_usage="usage: $0 find [serice:http|smb] PATTERN"

[ "$mode" = "find" ] && ! [ "$service" = "http" ] && ! [ "$service" = "smb" ] && echo $find_usage

[ "$mode" = "find" ] && [ "$service" = "http" ] && find $HOME/pt-resources -type f | sed "s|$HOME/pt-resources||g" | grep -i --color=always $pattern | while read line; do echo "http://$(get-vpn-ip || get-ip)$line"; done && exit 0

#[ "$mode" = "find" ] && [ "$service" = "smb" ] && find $HOME/pt-resources -type f | sed "s|$HOME/pt-resources||g" | sed 's|/|\\\\|g' | grep --color=always $pattern | while read line; do echo "\\\\\\\\$(get-vpn-ip || get-ip)$line"; done && exit 0

[ "$mode" = "find" ] && [ "$service" = "smb" ] && find $HOME/pt-resources -type f | sed "s|$HOME/pt-resources||g" | grep -i --color=always $pattern | sed 's|/|\\\\|g' | while read -r line; do echo "\\\\\\\\$(get-vpn-ip || get-ip)\\public$line"; done
