#!/bin/bash
# Simple network manager for Wi-Fi networks

template=$HOME/scripts/interfaces-template
wifidata=$HOME/scripts/wifi-data
networks=`grep id $wifidata | sed 's/.* //g'`
choice=`echo "$networks" | dmenu -p "Wi-Fi networks:"`
if [ ! -z $choice ]; then
    data=`grep -A2 "$choice$" $wifidata`
    if [ $choice == "eduroam" ]; then
        data=`grep -A6 "$choice$" $wifidata`
        echo $data
    fi
    sudo cp $template /etc/network/interfaces
    echo "$data" | sudo dd oflag=append conv=notrunc status=none of=/etc/network/interfaces
    sudo systemctl restart networking
    sudo cp $template /etc/network/interfaces
fi
